### ISSUE TITLE
sgpagingView 快速滑动页面错乱

### ISSUE THREAD

**Issue by hello3ds** [kingsic/SGPagingView#102]
集成sgpagecontentview  后页面快速滑动的时候，容易出现页面错乱，请问有遇到的吗？

**Comment by kingsic** [comment]
请提供所使用的版本号以及所使用的SGPageContent的哪个类 @hello3ds

**Comment by hello3ds** [comment]
- (SGPageContentView *)pageContentView{
    if (!_pageContentView) {
        _pageContentView = [[SGPageContentView alloc] initWithFrame:CGRectMake(0,kNavigationbarHeight + kTitleContainHeight, ScreenWidth, CGRectGetHeight(self.view.frame) - kTitleContainHeight) parentVC:self childVCs:self.viewControllers];
        _pageContentView.delegatePageContentView = self;
    
    }
    return _pageContentView;
}
用的是这个方法。version1.4.1.   不好意思，之前家里临时有事，忘记处理了

**Comment by kingsic** [comment]
使用最新版本1.5.1 ；1.4.几的版本由于更新导致一些问题；最新版本已修复一些问题




| |
kingsic
邮箱：kingsic@126.com
|

Signature is customized by Netease Mail Master

在2018年08月03日 11:40，hello3ds 写道：

(SGPageContentView *)pageContentView{
if (!_pageContentView) {
_pageContentView = [[SGPageContentView alloc] initWithFrame:CGRectMake(0,kNavigationbarHeight + kTitleContainHeight, ScreenWidth, CGRectGetHeight(self.view.frame) - kTitleContainHeight) parentVC:self childVCs:self.viewControllers];
_pageContentView.delegatePageContentView = self;

}
return _pageContentView;
}
用的是这个方法。version1.4.1. 不好意思，之前家里临时有事，忘记处理了
