### ISSUE TITLE
个别标题文字显示不全：[例...如]

### ISSUE THREAD

**Issue by BIMiracle** [kingsic/SGPagingView#105]
最新版本
![0a7d59ef5165e032a419991b491a9df1](https://user-images.githubusercontent.com/18730979/42978900-12057e92-8c02-11e8-90d2-48b94ee52b96.png)
![3dc271809a94d76f0ccaa94ed2d6fe72](https://user-images.githubusercontent.com/18730979/42978909-187bc344-8c02-11e8-8d9d-0454b57b1caa.png)
![b97f190299876714419346c4c2670bd0](https://user-images.githubusercontent.com/18730979/42978914-1ff9a3b6-8c02-11e8-92e8-76ea8b282d60.png)

`NSArray *titleArr = @[@"全部应用", @"我的应用", @"荣誉", @"团队", @"活动",@"1",@"2"];`

猜想:可能是数字字体宽度比较小,导致计算宽度不足一个屏幕时出错

**Comment by kingsic** [comment]
请根据 SGPageTitleViewConfigure 类中的 titleAdditionalWidth 属性来调试你想要的效果，建议各个尺寸的屏宽都要运行（4s～8p） @tryEvething
