### ISSUE TITLE
（偶现）多次滑动时会出现多个选中状态

### ISSUE THREAD

**Issue by wl199452** [kingsic/SGPagingView#106]

**Comment by hello3ds** [comment]
用的是sgpagecontentview   

- (SGPageContentView *)pageContentView{
    if (!_pageContentView) {
        _pageContentView = [[SGPageContentView alloc] initWithFrame:CGRectMake(0,kNavigationbarHeight + kTitleContainHeight, ScreenWidth, CGRectGetHeight(self.view.frame) - kTitleContainHeight) parentVC:self childVCs:self.viewControllers];
        _pageContentView.delegatePageContentView = self;
    
    }
    return _pageContentView;
}

版本是1.4.1
