### ISSUE TITLE
那个加入image 的能不能加入识别是 url ?

### ISSUE THREAD

**Issue by emodeqidao** [kingsic/SGPagingView#123]
[btn SG_imagePositionStyle:SGImagePositionStyleDefault spacing:spacing imagePositionBlock:^(UIButton *button) {
//在这里判断下 如果是url 那么 btn 加载那个url
            [btn setImage:[UIImage imageNamed:imageName] forState:btnControlState];
        }];

**Comment by WGQLoveCarol** [comment]
我需求里也遇到了

**Comment by kingsic** [comment]
新版本已支持 @brightbetter @emodeqidao
