### ISSUE TITLE
SGPageContentScrollView/ SGPageContentCollectionView 所包含的控制器视图显示不全

### ISSUE THREAD

**Issue by NuGelaLies** [kingsic/SGPagingView#125]
SGPageContentScrollView、SGPageContentCollectionView 添加控制器后，控制器的tableView/collectionView，上拉滑动无法显示全部cell。提供的Demo中静止样式选项也有相对应的问题[https://youtu.be/a1NUZGnucyY](url)

**Comment by zhenghongfeng** [comment]
我也遇到了 这个问题您解决了吗

**Comment by youzi001** [comment]
同样的问题 有解决吗

**Comment by AndreHu88** [comment]
> 我也遇到了 这个问题您解决了吗



> SGPageContentScrollView、SGPageContentCollectionView 添加控制器后，控制器的tableView/collectionView，上拉滑动无法显示全部cell。提供的Demo中静止样式选项也有相对应的问题[https://youtu.be/a1NUZGnucyY](url)

用这个SGPageContentCollectionView去初始化，没有这种问题。     SGPageContentScrollView初始化我也遇到了，第一个Controller的frame有问题的

**Comment by chuzhaozhi** [comment]
#213 这理由解决办法
