### ISSUE TITLE
左右滑动的时候，有时候会一下加载两个控制器

### ISSUE THREAD

**Issue by NumberTu** [kingsic/SGPagingView#134]
我的情况是：有四个控制器，经常从第一个滑到第二个的时候，会一下加载第二个和第三个控制器

**Comment by TML007** [comment]
我也遇到了

**Comment by NumberTu** [comment]
> 更新到作者的新版本，好像就没问题了

当时出现这个问题的时候，我就更新到最新了，但是并没有起作用
