### ISSUE TITLE
怎么设置不同长度的title 等间距分布

### ISSUE THREAD

**Issue by JLLJHD** [kingsic/SGPagingView#138]
怎么设置不同长度的title 等间距分布

**Comment by JLLJHD** [comment]
怎么设置不同长度的title 等间距分布

**Comment by kingsic** [comment]
本框架暂不支持这种需求<br>
可 fork 一份自己来维护<br>
参考资料 [SGRichView](https://github.com/kingsic/SGRichView) @JLLJHD
