### ISSUE TITLE
什么时候能支持masonry自动布局

### ISSUE THREAD

**Issue by Azraeltulips** [kingsic/SGPagingView#139]
希望能尽快更新可以支持masonry自动布局，灰常感谢

**Comment by kingsic** [comment]
1.6.0 已支持 @Azraeltulips

**Comment by Azraeltulips** [comment]
我忘了更新cocoapods了。。。。。

**Comment by ZCApple** [comment]
你好，我是用Swift写的项目，导入的是OC 1.6.0版的，用SnapKit布局不行，请教一下是什么原因呢？
