### ISSUE TITLE
指示器的宽度问题

### ISSUE THREAD

**Issue by TLQBlueWind** [kingsic/SGPagingView#14]
当滑动几次之后下面的指示器中心与上面文字的中心不一致，下面指示器会向右偏移
![img_0133](https://cloud.githubusercontent.com/assets/28774820/26489081/83c88eda-4238-11e7-8ad3-b92cbdae3725.PNG)

**Comment by kingsic** [comment]
测试并没有发现这样的问题，请将你的 Demo 私下发给我，进行调试 @TLQBlueWind

**Comment by TLQBlueWind** [comment]
我是在DefaultVCOne 这个控制器下添加了这样一句代码就 ：
 _pageTitleView.isOpenTitleTextZoom = YES;
我把这句代码去掉就是正常的
