### ISSUE TITLE
改变SGPageContentScrollView的frame时，SGPageContentScrollView上的UIScrollView的高度没有变化

### ISSUE THREAD

**Issue by Azraeltulips** [kingsic/SGPagingView#141]
改变SGPageContentScrollView的frame时，SGPageContentScrollView上的UIScrollView的高度没有变化
例如：懒加载SGPageContentScrollView的对象pageScrollView时，设置frame为（0，100，300，400）
在触发一个点击事件时，将pageScrollView的frame变为（0，0，300，500）。通过视图层次发现pageScrollView的高度变为了500，但是pageScrollView上的子控制器的高度还是400，没有跟着改变

**Comment by kingsic** [comment]
父视图的 frame 发生变化，子视图的 frame 也应该做出相应的调整，让子视图的  frame 随父视图的变化而变化即可<br>【注：不晓得你为什么要这样处理，本框架是不建议这样去处理的】 @Azraeltulips

**Comment by Azraeltulips** [comment]
产品要求啊，导航栏放个滑动菜单，头部放一个banner图，然后下面是可以滑动切换的列表。但是，banner图可以移除，这时，就需要重新调整，下面可以滑动切换的部分了。
