### ISSUE TITLE
v1.6.0 案例 Demo 【指示器遮盖样式三】崩溃问题

### ISSUE THREAD

**Issue by liudi0101** [kingsic/SGPagingView#146]
SGPagingViewExample[1275:214565] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 9223372036854775808 beyond bounds [0 .. 3]'

**Comment by kingsic** [comment]
崩溃（问题）导致的原因是：只有 PageContent 为 SGPageContentScrollView 且 selectedIndex != 0 与 insertSubview 方法同时出现造成的<br>
第一种解决方案：selectedIndex  != 0 与 insertSubview 方法同时存在，更换 SGPageContentScrollView 为 SGPageContentCollectionView 即可<br>
第二种解决方案：默认子控制器为0，即 selectedIndex 不设置<br>
第三种解决方案：insertSubview 更换为 addSubview
最后一种解决方案：PageContent 为 SGPageContentScrollView 且 selectedIndex  != 0 与 insertSubview 方法同时存在；代码处理如下：<br>
```
    [self.view addSubview:_pageContentScrollView];
    dispatch_async(dispatch_get_main_queue(), ^{
        [self.view insertSubview:self.pageContentScrollView atIndex:0];
    });
```
<br> @liudi0101

**Comment by kingsic** [comment]
如不需要使用 autolayout 创建，导入 v1.5.6 即可
