### ISSUE TITLE
1.6.1版本 多个控制器的时候，第一个控制的宽度会变为 750 的宽度  我将版本降至 1.5.5此问题消失

### ISSUE THREAD

**Issue by HoChiu** [kingsic/SGPagingView#161]

**Comment by kingsic** [comment]
测试并没有遇到你说的这种情况；你可以把你复现的代码发给我一份来调试 @HoChiu

**Comment by hkjin** [comment]
> 测试并没有遇到你说的这种情况；你可以把你复现的代码发给我一份来调试 @HoChiu

我也遇到这个问题，刚更新到1.6.1版本，第一个控制器确实变的很宽

`/// pageContentView
    lazy var pageContentView: SGPageContentScrollView = {
        let v = SGPageContentScrollView(frame: CGRect(x: 0, y: topSpace, width: kjSCREEN_WIDTH, height: kjSCREEN_HEIGHT - Utility.kjSNTHeight() - topSpace), parentVC: self, childVCs: kjChildViewControllers)
        v?.backgroundColor = UIColor(white: 1, alpha: 1)
        v?.delegatePageContentScrollView = self
        return v!
    }()
    `
下面是约束
`override func loadView() {
        super.loadView()
        /// titleView
        pageTitleView.snp.makeConstraints { (make) in
            make.size.equalTo(CGSize(width: 120.0, height: 44.0))
        }
        let space = UIBarButtonItem.qmui_fixedSpaceItem(withWidth: 5.0)
        let leftAction = UIBarButtonItem(customView: pageTitleView)
        navigationItem.leftBarButtonItems = [space, leftAction]
        /// contentView
        view.addSubview(pageContentView)
        pageContentView.snp.makeConstraints { (make) in
            make.edges.equalToSuperview().inset(UIEdgeInsets(top: topSpace, left: 0, bottom: 0, right: 0))
        }
    }`

**Comment by sjxt** [comment]
我也遇到这个问题了 楼上有解决吗？

**Comment by TML007** [comment]
我也遇到这个问题了 楼上有解决吗？

**Comment by purple-T** [comment]
@kingsic @HoChiu  @kj-huang @TML007 @sjxt 各位兄弟，我找到问题了。 SGPageContentScrollView文件中，在layoutSubviews中调用了[self P_layoutSubviews];  出现了问题。

////////修改如下////////

- (void)setupSubviews {
    // 0、处理偏移量
    UIView *tempView = [[UIView alloc] initWithFrame:CGRectZero];
    [self addSubview:tempView];
    // 1、添加 scrollView
    [self addSubview:self.scrollView];
    
    //在这里添加
    [self P_layoutSubviews];
}

#pragma mark - - - layoutSubviews
- (void)layoutSubviews {
    [super layoutSubviews];
    
//    [self P_layoutSubviews]; //注释掉
}

- (void)P_layoutSubviews {
    _scrollView.frame = self.bounds;
    CGFloat contentWidth = self.childViewControllers.count * _scrollView.SG_width;
    _scrollView.contentSize = CGSizeMake(contentWidth, 0);
}
