### ISSUE TITLE
SGPageTitleView 色彩设置方法

### ISSUE THREAD

**Issue by NineTD** [kingsic/SGPagingView#162]
- (void)resetTitleColor:(UIColor *)color titleSelectedColor:(UIColor *)selectedColor
这个方法在您的Demo DefaultScrollVC.m 里设置后出现：
1.点击后的btn色彩与所设置的色彩完全相反
2.再次点击相同btn，btn会变成默认的红色

**Comment by kingsic** [comment]
该方法暂与 configure.titleGradientEffect = YES; 不兼容 @NineTD
