### ISSUE TITLE
self.pageTitleView.selectedIndex = 1;不起作用怎么解决啊?

### ISSUE THREAD

**Issue by gouqituzi0117** [kingsic/SGPagingView#173]
想实现每次进入界面self.pageTitleView.selectedIndex = 1的需求,故在viewWillAppear加了这一句,但是只有第一次进入执行,

**Comment by Coastchb** [comment]
试试:
var target_index = 1
pageTitleView?.setPageTitleView(progress: 1.0, originalIndex: (pageTitleView?.index)!, targetIndex: target_index)
pageContentCollectionView?.setPageContentCollectionView(index: target_index)

**Comment by honeybeeSwinging** [comment]
第一次可以设置selectedIndex，第二次还需要选中其他的时候需要设置reselectedIndex
