### ISSUE TITLE
问题 + 建议用新版SGPagingView库写微博个人主页

### ISSUE THREAD

**Issue by TML007** [kingsic/SGPagingView#177]
用新版SGPagingView写微博个人主页会出现联动时候不能滑动的现象。老版1.4.2虽然有微博个人主页例子，一旦用新版的库就出现问题。

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
