### ISSUE TITLE
当标题个数较少时未居中问题

### ISSUE THREAD

**Issue by MrCoderMSH** [kingsic/SGPagingView#2]
当标题个数是2个或者是三个时  该控件无法在初始化的frame中居中显示，建议添加三个枚举状态：居中，左对齐，右对齐等类似的设置

**Comment by kingsic** [comment]
问题已经解决了 @MrCoderMSH

**Comment by MrCoderMSH** [comment]
没解决吧？
<img width="552" alt="qq20161117-0" src="https://cloud.githubusercontent.com/assets/13232963/20382048/27bee2f8-ace5-11e6-86db-8437bdcef8a7.png">

**Comment by MrCoderMSH** [comment]
一般情况下  segmentView的size.width = self.view.frame.size.width,这种情况时如果标题数组只有两个或者三个，甚至是一个时，会出现初始化完成时是左对齐，点击一次后变成右对齐了。其实是希望它是居中对齐

**Comment by kingsic** [comment]
那要看你是哪种情况了；标题数已经很少了，就选择静态的方法 SGSegmentedControlStatic @MrCoderMSH 
![simulator screen shot 2016 11 17 4 53 39](https://cloud.githubusercontent.com/assets/21109934/20382443/f19cedc6-ace6-11e6-95ca-56e617cea630.png)
