### ISSUE TITLE
viewWillAppear: 的触发问题, 也就是各子VC的生命周期不太清楚,能说明下么

### ISSUE THREAD

**Issue by AngryOC** [kingsic/SGPagingView#20]
pageContentView 放了四个子VC, (vc0,vc1,vc2,vc3),  当程序第一次进入SGPageView的superVC时, 展示的是vc0, 此时vc的viewWillAppear:方法被触发了, 当右滑显示vc1时, 会触发 vc1,vc2,vc3的viewWillAppear:  ;
而当不是第一次显示各个子vc时,  左滑右滑可能出发appear方法,也可能不会出发;

我这边需要 像 网易 新闻一样, 滑到某个子VC, 这个子VC自动下拉刷新, 而这个自动下拉刷新放在viewWillAppear:中,  由于ViewWillAppear: 出发的时机与UITabbarController 的子vc 不一样,  我这边效果不太好;

一次加载好几个子vc可能是collectionview的重用,  **那怎么才能做到 滑到一个子页面  该页面自动下拉刷新呢?**  

在代理方法[setPageTitleViewWithProgress: originalIndex:  targetIndex:] 实现么 ,准备试试看看;

**Comment by kingsic** [comment]
新增滚动内容样式，采用 UIScrollView，滚动结束之后加载子视图 @AngryOC
