### ISSUE TITLE
到后台再次进入demo有问题

### ISSUE THREAD

**Issue by dongziGuo** [kingsic/SGPagingView#208]
首先说一下,这个控件使用起来简单又方便,真香的典范
但是我偶尔发现点击后面的title后,滑倒后台,有时候(大概率)出现自动回到第一个title选中状态,如果没发现这个问题那么在后台停留的时间长一点试试,如果还是没有发现,那就多点几下试试,由于能力有限,暂时没有发现问题原因

**Comment by dongziGuo** [comment]
- (void)pageTitleView:(SGPageTitleView *)pageTitleView selectedIndex:(NSInteger)selectedIndex;在这个点击事件中要给selectedIndex属性赋值就是合适的

**Comment by kingsic** [comment]
最新版本已修复，感谢反馈 @dongziGuo
