### ISSUE TITLE
 tabbar 不能隐藏

### ISSUE THREAD

**Issue by Kittycats** [kingsic/SGPagingView#24]
在pageContentView管理下的界面里放一个 tableView, 点击 tableView 的 cell 跳转下级页面时, tabbar 不能隐藏

**Comment by hao1993** [comment]
自己手动隐藏呀，

**Comment by Kittycats** [comment]
就是手动隐藏不了 啊

**Comment by Kittycats** [comment]
你自己建一个 tabbar 管理下的视图, 试试能隐藏不

**Comment by Kittycats** [comment]
我知道是手动隐藏, 我项目是在 tabbar 管理下的, 引入这个后, 在分段控制器的一个页面是个 tabbleView, 点击 cell 跳转页面的时候, tabbar 隐藏不了, 
  self.hidesBottomBarWhenPushed = YES;
  self.hidesBottomBarWhenPushed = NO;

无效

**Comment by zhanglele1** [comment]
请问你这个不能隐藏的问题解决了嘛
