### ISSUE TITLE
程序崩溃

### ISSUE THREAD

**Issue by ShenZhenChenlin** [kingsic/SGPagingView#3]
在滚动状态下的带图片的导航栏，如果快速地连续地侧滑控制器的视图，会出现程序意外退出。出错地原因是在当前选中的标签显示的控制器一直快速切换，还没有来得及根据水平方向的位置便宜就执行切换控制器，计算数组下标索引递增，造成数组越界

**Comment by kingsic** [comment]
你说的这个问题我试了一下，确实存在的；我想知道你的手速要有多快 😄😄 @ShenZhenChenlin

**Comment by kingsic** [comment]
bug 问题已经修复了 @ShenZhenChenlin
