### ISSUE TITLE
子控制器的生命周期 都完全 不对了

### ISSUE THREAD

**Issue by lahala** [kingsic/SGPagingView#30]

**Comment by lahala** [comment]
已找到解决方法，即在添加子控制器时，添加这行代码： [childVC beginAppearanceTransition:YES animated:YES];

**Comment by kingsic** [comment]
感谢你发现了这个问题，请不要加上这句代码，详细介绍请看问题及解决方案第二条 @lahala

**Comment by Liyongcong** [comment]
方案并没解决
