### ISSUE TITLE
NavigationBarVC这个界面出现的这个问题，xcode 9 iphone7 ios 11.0

### ISSUE THREAD

**Issue by JIAZoro** [kingsic/SGPagingView#35]
![simulator screen shot - iphone 7 - 2017-10-31 at 11 02 06](https://user-images.githubusercontent.com/14291400/32205575-f53a1098-be2a-11e7-8dd5-9bc85ab37a4d.png)

**Comment by LeeJunhui** [comment]
我测试的时候也发现了这个问题

**Comment by kingsic** [comment]
已适配 iOS 11 的系统 @JIAZoro @LeeJunhui
