### ISSUE TITLE
SGPageContentView有问题

### ISSUE THREAD

**Issue by XiMuYouZi** [kingsic/SGPagingView#36]
SGPageContentView有问题，因为是使用collecview来实现的，cell的重用机制导致如果cell不在屏幕上就会被回收，那么添加在cell上面的childVC的view就没了，这个时候如果要调用该childvc来做一些事情就会有问题

假设有三个childvc，我滑动到最后一个，理论上应该全部加载完了，但是我再随机滑动，会出现有的子childvc的viewdidload方法再次调用，说明该子childvc的view被回收了

可以使用SGPageContentScrollView来实现是一次全部加载完毕，还是滑动后在加载

**Comment by kingsic** [comment]
第一个问题是cell的循环机制导致你的疑惑，由于子控制器添加到父控制器中，子控制器只会被加载一次，子控制器的 viewDidLoad 只会被触发一次，而 cell 不在屏幕上时，子控制器 view 是被移到缓存池中，如果再次出现在屏幕的时候，会从缓存池再次取出，你可以打印子控制器的 viewDidLoad 方法，看一下其调用次数
第二个问题，采用的是视图加载完成之后显示其内容，而不是一下子全部加载完毕，这里之所以这样做是考虑到 app 的性能问题，当你需要时候才会加载，不需要的时候不会被加载
你可以看一下手机上的这一模块的 app ，都是这 2 种形式，这就是为什么后来添加了 SGPageContentScrollView 类的原因 @XiMuYouZi

**Comment by XiMuYouZi** [comment]
恩，理解你说的。

主要是第一点问题，子控制器的view被移到了缓存池，导致该子控制器没法响应事件调用了。

例如我遇到的一个问题：我在三个子控制器里面都埋点接受同一个通知事件，这三个子控制器也都加载了。但是我在其他地方发送通知事件的，发现三个控制器会随机出现有的子控制器没法接受到通知

另外也由于cell的重用机制导致childvc的view会被随机加载，可能已经加载过得childvc的view，滑回来的时候又被加载了一次，其实这是没必要的。

因为有时候需要所有view都被一次加载完毕，并且加载完了后，这些view就一直存在，而collectionview会出现即使这些childvc的view被加载过了，滑动回来，依然会再次加载。
更严重的问题就是我上面说的，用于被移除了，根本就不响应事件了

**Comment by kingsic** [comment]
嗯嗯，我在问题及解决方案中做了对 SGPageContentView 与 SGPageContentScrollView 数据处理问题的说明；你可以根据你项目的需求，适当的更改源码 @XiMuYouZi

**Comment by XiMuYouZi** [comment]
好的
