### ISSUE TITLE
为什么 设置了indicatorColor 不生效

### ISSUE THREAD

**Issue by emodeqidao** [kingsic/SGPagingView#49]
为什么 设置了indicatorColor 不生效

**Comment by emodeqidao** [comment]
SGPageTitleViewConfigure *configure = [SGPageTitleViewConfigure pageTitleViewConfigure];
    configure.indicatorHeight = 2;
    configure.titleColor = SetColor(ASC_grayColor_4C4447);
    configure.titleSelectedColor = SetColor(ASC_pinkColor_ff6b8f);
    configure.indicatorColor = SetColor(ASC_grayColor_4C4447);
    configure.indicatorAdditionalWidth = 100; // 说明：指示器额外增加的宽度，不设置，指示器宽度为标题文字宽度；若设置无限大，则指示器宽度为按钮宽度
    
    /// pageTitleView
    self.pageTitleView = [SGPageTitleView pageTitleViewWithFrame:CGRectMake(0, pageTitleViewY, self.view.frame.size.width, 44) delegate:self titleNames:titleArr configure:configure];
    self.pageTitleView.configure.titleSelectedColor = SetColor(ASC_pinkColor_ff6b8f);
    self.pageTitleView.configure.indicatorColor = SetColor(ASC_pinkColor_ff6b8f);
    self.pageTitleView.configure.titleColor = [UIColor lightGrayColor];
    self.pageTitleView.configure.indicatorBorderColor = SetColor(ASC_pinkColor_ff6b8f);
    [self.view addSubview:_pageTitleView];

**Comment by kingsic** [comment]
SGPageTitleView 的配置信息 SGPageTitleViewConfigure 是在初始化进行配置的；SGPageTitleView.h 文件提供 configure 属性，是告诉开发者这是一个配置信息，但不希望开发者在创建好 SGPageTitleView 之后再次拿到进行 SGPageTitleViewConfigure 属性设置

**Comment by kingsic** [comment]
SGPageTitleView 的配置信息 SGPageTitleViewConfigure 是在初始化进行配置的；SGPageTitleView.h 文件提供 configure 属性，是告诉开发者这是一个配置信息，但不希望开发者在创建好 SGPageTitleView 之后再次拿到进行 SGPageTitleViewConfigure 属性设置 @emodeqidao

**Comment by emodeqidao** [comment]
ok  收到  @kingsic  去掉下面的设置就可以生效了
