### ISSUE TITLE
更改了指示器的宽度，在plus 屏幕情况下，指示器不能正确对齐，请看下图

### ISSUE THREAD

**Issue by yangzheng006** [kingsic/SGPagingView#68]
![wechatimg51](https://user-images.githubusercontent.com/10958391/37381388-d8970b7e-2777-11e8-9e30-12e2c8a9d955.jpeg)

**Comment by hgpll** [comment]
选中的字体大小 怎么修改的

**Comment by yangzheng006** [comment]
@hgpll 没有开放这个属性，我就是用的放大

**Comment by kingsic** [comment]
选中字体大小属性已经开发 @yangzheng006 @hgpll

**Comment by hgpll** [comment]
@kingsic ..在你框架的基础上，我已经改好了，谢谢啦～～
