### ISSUE TITLE
不支持autolayout？还是设置frame的方式？

### ISSUE THREAD

**Issue by czl0325** [kingsic/SGPagingView#73]
不支持autolayout？还是设置frame的方式？

**Comment by atom2ueki** [comment]
@czl0325 目前是设置frame的方式，因为原作者把计算button坐标的func放在了init里面，那时候`- (void)layoutSubviews`还没来得及trigger，所以直接用autolayout的宽度是有问题的，需要改一些地方，晚些时候我会提一个pr，我本地的已经改好了
