### ISSUE TITLE
快速切换子页面的时候会出现错乱！！

### ISSUE THREAD

**Issue by LspPengPeng** [kingsic/SGPagingView#87]

**Comment by fengqiangboy** [comment]
我也发现了

**Comment by fengqiangboy** [comment]
改成  SGPageContentScrollView 可以，应该是SGPageContentView的BUG

**Comment by ThatMan666** [comment]
SGPageContentView和SGPageContentScrollView区别是什么?

**Comment by loveJuly** [comment]
改成SGPageContentScrollView，左右滑的时候上下不联动
