### ISSUE TITLE
文字缩放效果，退至后台，再进来，再滑动，字体的问题

### ISSUE THREAD

**Issue by AbnerPei** [kingsic/SGPagingView#95]
1. 运行demo，打开“文字缩放效果”
2. 手机摁home键盘；
3. 再次打开demo,
4， 滑动，上次滑动到的文字保持放大状态，当前文字不放大

**Comment by chinesemanbobo** [comment]
补充说明下，我没有设置titleSelectedFont属性，但是，从后台就来就出现了问题：后来经过我的测试，我发现：UIFont也是有缓存的，个人初步猜测是缓存池机制（在没有退至后台前，不是默认configure设置了titleSelectedFont的属性是[UIFont systemFontOfSize:15],这时候会生成一个font对象，假如内存地址为<0x78678034ea>，这时候走到- (void)setPageTitleViewWithProgress:(CGFloat)progress originalIndex:(NSInteger)originalIndex targetIndex:(NSInteger)targetIndex 方法里的if (self.configure.titleSelectedFont == [UIFont systemFontOfSize:15]) {时，[UIFont systemFontOfSize:15]按道理来说应该会重新创建一个font对象，可是并没有，系统在缓存池中找到了刚创建的<0x78678034ea>font，就是想要的大小为15的font，就返回给你了，**可是**，注意了，如果你摁了home键，系统会立马清理缓存池中的<0x78678034ea>font，在你走上面的判断时，[UIFont systemFontOfSize:15]这时候就无法取缓存里了，因为缓存里没有了，所以就相当于新alloc一个，内存地址肯定不是<0x78678034ea>，而是其它的比如<0x8976wr7845>,所以 == 不成立，就出现了bug）.

整体来说，作者的库很给力，尤其配置configure的设置，是我喜欢的。赞一个。

感谢开源，我也贡献我的一份薄利。

### 具体修改方案如下：
` // 5 、标题文字缩放属性(开启文字选中字号属性将不起作用)
    if (self.configure.titleSelectedFont == [UIFont systemFontOfSize:15]) {`

修改为：

`UIFont *configureFont = self.configure.titleSelectedFont;
    UIFont *defaultFont = [UIFont systemFontOfSize:15];
    if ([configureFont.fontName isEqualToString:defaultFont.fontName] && configureFont.pointSize == defaultFont.pointSize) {`

**Comment by kingsic** [comment]
最新版本已修复这个问题
